name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: |
          "pip install poetry"
          "make install"
          "source .venv/bin/activate"
          "make lint"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          "pip install poetry"
          "make install"
          "source .venv/bin/activate"
          "make test"