name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install Poetry
        run: pip install poetry
      - name: Intall dependencies
        run: poetry install
      - name: Lint
        run: make lint