name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Intall dependencies
        run: poetry install
      - name: Lint
        run: poetry run pylint nbr tests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install poetry
        run: pip install poetry
      - name: Intall dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest tests
      - name: Coverage
        run: coverage xml -o coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2