name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Intall dependencies
        run: poetry install
      - name: Lint
        run: poetry run pylint nbr tests

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Intall dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest tests